title: Leopoldo Zugasti
logo: /assets/img/logo.png
description: Software Engineer, specializing in Web development and Graphics Engineering
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
